### ISSUE TITLE
No accented characters?

### ISSUE THREAD

**Issue by Pointedstick** [salty-horse/ibus-uniemoji#16]
Try as I might, I can't figure out how to make this amazing little piece of software help me type accented characters. Maybe that's not implemented? If not, here's a vote for it!

**Comment by salty-horse** [comment]
The tool only comes pre-loaded with various symbols and emoji.

If you want, you can add accented characters in a personal configuration file.
Edit `~/.config/uniemoji/custom.json` to include something like:
```json
{
	"e'": "é"
}
```

Now when you type `e'`, "é" will show up as an option.

**Comment by Pointedstick** [comment]
Oh, cool.
