### ISSUE TITLE
Color emoji in the selection menu

### ISSUE THREAD

**Issue by NieDzejkob** [salty-horse/ibus-uniemoji#19]
Currently the black and white font is used for emoji in the selection menu. This looks awful.

**Comment by salty-horse** [comment]
I don't think IBus lets you embed images. Either that happens, or the OS gets support for displaying images in fonts.

Sorry :(

**Comment by Depaulicious** [comment]
I read somewhere (I think OMG Ubuntu) that they're going to add support for color emoji in GTK. Is the IBus selector GTK based?

**Comment by salty-horse** [comment]
Maybe...? But I'm using an OpenType SVG font and it only shows in color in
Firefox.

**Comment by astronouth7303** [comment]
I suspect It Varies, since the ibus engines don't define much about the UI, it might be up to the receiving end what widgets they use.

But if your font engine supports color emoji, it might happen to you transparently with no changes to ibus-uniemoji. (Maybe. Font selection is Complicated.)

**Comment by salty-horse** [comment]
[Cairo 1.15.8](https://cgit.freedesktop.org/cairo/tree/NEWS?id=1.15.8) has been released, with support for rendering color emoji glyphs, which also means they appear as color in the IBus selection menu.

Hurray and thanks to the developers!
