### ISSUE TITLE
Doesn't depend on python-ibus anymore

### ISSUE THREAD

**Issue by jcharaoui** [salty-horse/ibus-uniemoji#20]
The python-ibus package was deprecated and isn't provided anymore in recent releases of Debian/Ubuntu. It used to provide the python-gtk2 ibus bindings. See this [commit log](https://anonscm.debian.org/cgit/pkg-ime/ibus.git/commit/debian/control?id=799392ec52fd9f69de368189976c27a69781f545) for the details.

**Comment by salty-horse** [comment]
ibus-uniemoji doesn't use python-ibus, and has used gobject introspection since its inception

Is this a bug report? Can you be more specific about your issue? Which version of ibus-uniemoji are you using?

**Comment by jcharaoui** [comment]
This is a bug report against the README, which states that (obvious) dependencies include "the ibus python bindings (on debian/ubuntu: ibus-python)". That line should be removed. This package never existed, the correct package name was python-ibus, and it's not shipped anymore in Debian/Ubuntu.

**Comment by salty-horse** [comment]
Fixed in f7ba7efe0eac8f1f1848fa6af4f5d1d2ca4c6e16. Thanks!
