### ISSUE TITLE
Dropdown list appears in bottom-left corner of the screen

### ISSUE THREAD

**Issue by jcharaoui** [salty-horse/ibus-uniemoji#21]
According to the example shown in the README, the dropdown list should appear under the word being typed, correct? See this example: https://imgur.com/i7xXtgH

Also, most emoji appear as white squares, but perhaps I just may be missing some fonts.

This is using Debian 9 (stretch) with GNOME 3.22

**Comment by salty-horse** [comment]
Yes, it should appear under the cursor. I tried it in LibreOffice Writer and it works as expected, not like it is in your video.

Have you tried it in other applications? I'm not sure what causes it, but it's likely more related to IBus. uniemoji uses this mechanism without controlling where the box is displayed.

I suggest installing the font [Symbola](http://users.teilar.gr/~g1951d/), which has glyphs for most Unicode codepoints, specifically emoji, and [twemoji-color-font](https://github.com/eosrei/twemoji-color-font), which provides color emoji glyphs, but those will only appear in color in Gnome 3.26, which was just released.
