### ISSUE TITLE
[Enhancement] Lighten up unselected icons in emoji selector

### ISSUE THREAD

**Issue by Depaulicious** [salty-horse/ibus-uniemoji#22]
I'm using Ubuntu Bionic, which includes latest GTK3 with color emoji support, so the emoji selector now shows color emoji (😍).

This highlights a little glitch: the selected emoji is perfectly colored, however the unselected ones are a bit darkened, and that makes them look not really good (see screenshot).

Is it possible to lighten them up?

![Screenshot](https://i.imgur.com/XZ9HYEI.png)

🏳️‍🌈💡➕🔝

**Comment by salty-horse** [comment]
I should upgrade to Bionic as I don't yet have those icons :)

I think this is a UI theme issue - the same one that causes the text in unselected to appear white, and text in selected entries to appear grey. I'll try asking around. I'm closing this, as this isn't in this project's control, but we can keep discussing it here.

**Comment by Depaulicious** [comment]
I'm using Android 8's NotoColorEmoji.ttf font, which you can `adb pull` out of your phone or extract from a rom :)

**Comment by salty-horse** [comment]
A font isn't enough. I'm missing the latest versions of some of the display libraries.
