### ISSUE TITLE
Popup doesn't show

### ISSUE THREAD

**Issue by gabrielschulhof** [salty-horse/ibus-uniemoji#37]
Here are the steps I performed:

0. `git clone https://github.com/salty-horse/ibus-uniemoji`
0. `cd ibus-uniemoji`
0. `sudo make install`
0. `ibus restart`
0. Added uniemoji to list of used input methods
0. Switched to uniemoji
0. Typed "world" and hit enter - got a map-of-the-world emoji

The problem is that as I was typing the letters of "world" I did not see a popup with all the options as constrained by what I had typed so far.

How can I coax the popup into appearing?

**Comment by salty-horse** [comment]
I think this is an iBus issue. Can you try with the Pinyin input method? It also uses a popup.

**Comment by gabrielschulhof** [comment]
Actually, the popup appears, but it's in a really weird location. The placement calculation is wrong.

**Comment by gabrielschulhof** [comment]
You're right – that one has the same problem.

**Comment by salty-horse** [comment]
You can try reporting it to the [IBus project](https://github.com/ibus/ibus).
