### ISSUE TITLE
Install to /usr/local/ doesn't appear to be recognised by ibus

### ISSUE THREAD

**Issue by iam-TJ** [salty-horse/ibus-uniemoji#38]
Using Xubuntu 18.04 and installing with PREFIX=/usr/local the ibus engine doesn't seem to be found.

It isn't listed by "ibus list-engine" and there is no "Other" category in Preferences > Input Methods > Add when the offered list has been expanded.

**Comment by salty-horse** [comment]
Did you configure ibus to look for components in `/usr/local/share/ibus/components`? By default it looks in `/usr/share/ibus/component` only.

The ibus manpage suggests you can configure extra paths with the `IBUS_COMPONENT_PATH` environment variable. Try running ibus-daemon with `IBUS_COMPONENT_PATH=/usr/share/ibus/component:/usr/local/share/ibus/components`.

**Comment by iam-TJ** [comment]
No, I didn't, and didn't spot that mention in the "write-cache" option of the man-page. Thanks for pointing it out.

I went ahead and uninstalled using the PREFIX=/usr/local and re-installed to the default prefix and now it is seen, but has provoked another problem which I'd best open a new issue about!

**Comment by salty-horse** [comment]
Can this bug be closed?
