### ISSUE TITLE
How to determine if uniemoji is working?

### ISSUE THREAD

**Issue by iam-TJ** [salty-horse/ibus-uniemoji#39]
Having installed on Xubuntu 18.04 amd64, configured it in ibus, and it being one of two input methods now listed, I'm not able to get it to work.

However, because I'm not entirely sure what to expect I'm struggling to diagnose the issue.

For starters, when uniemoji is in the list of methods should there be an ibus-uniemoji process running alongside the other ibus processes? I only see:

```
ps -efly | grep ibus
S tj       24070     1  0  80   0  7540 90408 poll_s 16:57 ?        00:00:44 /usr/bin/ibus-daemon --daemonize --xim --address unix:tmpdir=/tmp/ibus
S tj       24082 24070  0  80   0  6708 70198 poll_s 16:57 ?        00:00:00 /usr/lib/ibus/ibus-dconf
S tj       24083 24070  0  80   0 35428 117715 poll_s 16:57 ?       00:00:02 /usr/lib/ibus/ibus-ui-gtk3
S tj       24087     1  0  80   0 20156 81973 poll_s 16:57 ?        00:00:30 /usr/lib/ibus/ibus-x11 --kill-daemon
S tj       24090  4019  0  80   0  5788 69642 poll_s 16:57 ?        00:00:00 /usr/lib/ibus/ibus-portal
S tj       24115 24070  0  80   0  6316 51225 poll_s 16:57 ?        00:00:16 /usr/lib/ibus/ibus-engine-simple
```
I've tried it in mousepad, xfce4-terminal, tmux, weechat, firefox, thunderbird and not had any success.

I've tried pressing the Super+Space hotkeys and there appears to be a definite pause after I type the first character of, for example, "man" and the "m" never appears but then the "an" does appear but no pop-up menu or other indication that uniemoji is active.

ibus-config confirms it is all enabled and I can use the ibus emoji Ctrl+Shift+E to bring up the internal emoji chooser, which suggests ibus is working as intended.

**Comment by salty-horse** [comment]
You should see the process `/usr/bin/python3 /usr/share/ibus-uniemoji/ibus.py --ibus` with the parent `ibus-daemon --xim --panel disable`.

If you click on the ibus indicator (typically showing "en" for english, you should see a menu with the option "Other (uniemoji) 🐱".

Once chosen, typing anything will open up the context menu.

Maybe `ibus-daemon`'s stdout/stderr can provide more clues?

**Comment by iam-TJ** [comment]
Thanks. As I suspected the process isn't starting, or is failing when called. It is listed in the ibus indicator.

Looks like there's some configuration fragment left over from the PREFIX=/usr/local installation, since when pressing Super+Space to switch to uniemoji I see:
```
$ ibus-daemon -v --replace --xim --address unix:tmpdir=/tmp/ibus

(ibus-ui-gtk3:2520): IBUS-WARNING **: 23:49:07.867: panel.vala:308: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:2520): IBUS-WARNING **: 23:49:07.923: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:2520): Gdk-CRITICAL **: 23:49:07.968: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/bin/python3: can't open file '/usr/local/share/ibus-uniemoji/ibus.py': [Errno 2] No such file or directory
```
That was it; there's a bugette in the Makefile. After doing `make PREFIX=/usr/local uninstall`  the clean target ought to be called so that `uniemoji.xml` and `config.py` are re-generated next time `make install` is called.

Many thanks for your swift assistance.

Now I have to figure out why Super+Space isn't actually switching the input method - had to use the tray applet menu to do it. Hopefully it's just something else has that key binding.

**Comment by salty-horse** [comment]
I will check the Makefile bug.

For the hotkey, try changing it to something else and see if it works.

**Comment by iam-TJ** [comment]
The hot-key issue turned out to be the system keyboard mapping was wrong.

Installed on an Asus T300CHI so chose, quite obviously, "Asus Laptop" as the keyboard model (using `dpkg-reconfigure keyboard-configuration`).

Turns out that causes the Windows Logo 'Super' key to generate the `Multi_key` event not  `L_Super`. 

Switched to the "Generic 102 keys" model and it now works perfectly.

**Comment by salty-horse** [comment]
Having the makefile detect changes in env variables can [be cumbersome](https://www.cmcrossroads.com/article/rebuilding-when-cppflags-changes). I'm considering leaving it as-is. (I also don't like the alternative of having it always rebuild.)

Do you think this is important to handle correctly? You're usually only calling it once when installing.

**Comment by iam-TJ** [comment]
Considering the two targets `uniemoji.xml` and  `config.py` simply trigger a `sed` replacement I don't think in this case any env-var detection is needed.

Doing a `clean` operation after `uninstall` (or simply deleting those two build products) would ensure any subsequent build is correct.
