### ISSUE TITLE
works in gedit, libreoffice, and gnome-terminal; doesn't work in firefox, chromium, nor signal

### ISSUE THREAD

**Issue by meonkeys** [salty-horse/ibus-uniemoji#44]
I think I have everything installed correctly... I see the input mode switcher indicator icon in the systray and super-space toggles between "en" and the cat face.

The emoji picker works as expected in gedit, libreoffice, and gnome-terminal. It doesn't work in firefox, chromium, nor signal.

I'm using Ubuntu 22.04 LTS desktop and the Debian package from the `helkaluin/ibus-uniemoji` ppa.

**Comment by salty-horse** [comment]
This seems like an IBus issue, and not something specific to this plugin.

Unfortunately, I don't know much about IBus works, and am also suffering from some of its quirks. Have you tried looking for similar issues specific to chromium and ibus? For example, this [askubuntu question](https://askubuntu.com/questions/1412097/chrome-or-chromium-can-not-use-ibus).

**Comment by meonkeys** [comment]
Thank you. I rebooted and it started working. :shrug:
