### ISSUE TITLE
Cannot type with uniemoji after selecting it in ibus

### ISSUE THREAD

**Issue by protist** [salty-horse/ibus-uniemoji#9]
I tried installing ibus-uniemoji from Arch Linux's AUR. I tried both [ibus-uniemoji](https://aur.archlinux.org/packages/ibus-uniemoji/) and [ibus-uniemoji-git](https://aur.archlinux.org/packages/ibus-uniemoji-git/). However neither seems to be working for me.

ibus appears to be working fine. I have enabled uniemoji in the setup. I can switch between English and (say) Arabic, which does change the input when I type. I can even select Uniemoji as a language. However, text just appears as normal, in the previously-selected language. No pop-up appears.

I'm not sure if dependencies are to blame. There is no ibus-python or similar in Arch Linux that I can see. I think "the ibus gobject introspection information" is [installed](https://www.archlinux.org/packages/extra/x86_64/python-gobject/) as a dependency to ibus. I'm not sure where ibus logs are or how to debug, but I'm happy to provide more information if necessary.

**Comment by astronouth7303** [comment]
Is uniemoji running?

**Comment by protist** [comment]
> Is uniemoji running? Or can you run it manually?

I'm not sure how to tell. I'm not sure how to run it manually.

> Is it available as an input option?

I selected it as an input option in `ibus-setup`. I can switch to it, with the ibus OSD and the tray icon both confirming that I'm using uniemoji.

**Comment by astronouth7303** [comment]
> I'm not sure how to tell. I'm not sure how to run it manually.

Check the process list. Run `/usr/share/ibus-uniemoji/uniemoji.py` and see what comes out on stdout/stderr.

**Comment by protist** [comment]
After I switch to uniemoji in ibus, I can see the following process.
```
python2 /usr/share/ibus-uniemoji/uniemoji.py --ibus
```

If I try to run uniemoji manually, it gives the following warning:
```
$ /usr/share/ibus-uniemoji/uniemoji.py
/usr/share/ibus-uniemoji/uniemoji.py:25: PyGIWarning: IBus was imported without specifying a version first. Use gi.require_version('IBus', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import IBus
```
There is no pop-up or any other kind of feedback. I can see the following process this time.
```
python /usr/share/ibus-uniemoji/uniemoji.py
```
I thought this might be an issue with Arch's default python 3, so I launched it with `$ python2 /usr/share/ibus-uniemoji/uniemoji.py`. However, I get the identical error and no feedback again.

**Comment by astronouth7303** [comment]
It's just a warning, doesn't matter.

It shouldn't pop up immediately. You have to type the name of an emoji first.

**Comment by protist** [comment]
Ah yes, sorry, I did try that too. I switch to uniemoji in ibus, then start typing, and nothing pops up.

**Comment by astronouth7303** [comment]
It uniemoji does appear in the process when you switch to it, even if you didn't start it by hand, right?

**Comment by protist** [comment]
Yes. If I switch to uniemoji in ibus, I can see the process appear.

**Comment by salty-horse** [comment]
This sounds like an IBus issue, and I'm not that familiar with it. Let's try a few things:

1. Can you try adding the Chinese Pinyin input method and see if its pop up a menu when you start typing?
2. When you type in UniEmoji mode, the *previous* input mode has to be English, otherwise it won't complete anything. When you do type English, does the text have an underscore?

**Comment by protist** [comment]
> Can you try adding the Chinese Pinyin input method and see if its pop up a menu when you start typing?

Yes, this doesn't work at all. I'm obviously facing a general ibus problem, which is clearly beyond the scope of this project, so I'm willing to troubleshoot myself, if you like.

> When you do type English, does the text have an underscore?

No, it doesn't.

**Comment by salty-horse** [comment]
> I'm obviously facing a general ibus problem, which is clearly beyond the scope of this project, so I'm willing to troubleshoot myself, if you like.

If we've established it's a general problem, yes. Do you mind if I close this? It would be helpful if you post your findings here, once you figure out the problem.

**Comment by protist** [comment]
No worries. I'll definitely post back when (if) I find the solution. Thanks for the help anyway.
